openapi: 3.0.3
info:
  title: Spring Boot Demo API
  version: 1.0.0
paths:
  /stocks:
    get:
      summary: Get all stocks
      description: Retrieves the current state of the board and the winner.
      tags:
        - Stocks
      operationId: getAllStocks
      responses:
        200:
          description: Success
  /stocks/{stockId}:
    get:
      summary: Get a stock by stock identifier
      description: Retrieves the current state of the board and the winner.
      tags:
        - Stocks
      operationId: getStockById
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stock'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    stock:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 12345
        date:
          type: string
          format: date-time
    error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        description:
          type: string
